services:

  database:
    container_name: database
    build:
      context: ./infra/postgres

  broker:
    container_name: broker
    build:
      context: ./infra/broker

  nginx:
    container_name: nginx
    build:
      context: ./infra/nginx
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Mapear a pasta dos arquivos static para que o nginx possa servi-los
      # - ./apis/core_app/static:/static
    ports:
      - "8000:80"
