# Generated by Django 4.2.11 on 2024-07-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="layout",
        ),
    ]
