# Generated by Django 4.2.11 on 2024-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_chair_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="chair",
            name="hold_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Time limit for a reservation. After this time the chair will be available again.",
                null=True,
            ),
        ),
    ]
